import { Routes, Route, Link } from "react-router-dom";
import HomePage from "./pages/HomePage.jsx";
import VotePage from "./pages/VotePage.jsx";
import ResultPage from "./pages/ResultPage.jsx";
import FinalPage from "./pages/FinalPage.jsx";
import RoundButton from "./components/RoundButton/RoundButton.jsx";
import PillButton from "./components/PillButton/PillButton.jsx";
import Card from "./components/Card/Card.jsx";

import { FontAwesomeIcon } from "@fortawesome/react-fontawesome"
import { faHouse } from "@fortawesome/free-solid-svg-icons";
import { faArrowRotateLeft } from "@fortawesome/free-solid-svg-icons";
import { faArrowRight } from "@fortawesome/free-solid-svg-icons";

export default function App() {
  const items = [
    { id: 0, src: '#', type: 'AI-GENERATED', ai_vote: 0, human_vote: 0, description: 'NULL' },
    { id: 1, src: '/img/astronaut.jpg', type: 'AI-GENERATED', ai_vote: 0, human_vote: 0, description: 'An Astronaut' },
    { id: 2, src: '/img/flamingone.jpg', type: 'HUMANMADE', ai_vote: 0, human_vote: 0, description: 
        `Miles Astray’s picture “F L A M I N G O N E” won the People’s Vote and a Jury Award in the artificial intelligence category of 1839 Awards 
        The twist was: Artificial intelligence had nothing to do with Astray’s photo. He shot it with a camera. And that’s why it later got disqualified from the 1839 Awards.` },
    { id: 3, src: '/img/building.jpg', type: 'HUMANMADE', ai_vote: 0, human_vote: 0, description: 'Todor, our teammate, took this photo with his phone!!!' },
    { id: 4, src: '/img/Midjourney.jpg', type: 'AI-GENERATED', ai_vote: 0, human_vote: 0, description: 
        `In August 2022, Allen, a game designer who lives in Pueblo West, Colorado, won first place in the emerging artist division’s “digital arts/digitally-manipulated photography” category at the Colorado State Fair Fine Arts Competition.<br>
        His winning image, titled “Théâtre D’opéra Spatial” (French for “Space Opera Theater”), was made with Midjourney — an artificial intelligence system that can produce detailed images when fed written prompts. A $300 prize accompanied his win.` },
    { id: 5, src: '/img/dog.jpg', type: 'HUMANMADE', ai_vote: 0, human_vote: 0, description: 'Real image by Toni Frissell, 1958. Sourced from Flickr.' },
    { id: 6, src: '/img/burger.jpg', type: 'AI-GENERATED', ai_vote: 0, human_vote: 0, description:  `AI image generated by Gemini, using the prompt “generate a realistic image of a hamburger, suitable for an ad.”` },
    { id: 7, src: '/img/astronaut.jpg', type: 'AI-GENERATED', ai_vote: 0, human_vote: 0, description: 'An Astronaut' },
    { id: 8, src: '/img/astronaut.jpg', type: 'AI-GENERATED', ai_vote: 0, human_vote: 0, description: 'An Astronaut' },
    { id: 9, src: '/img/astronaut.jpg', type: 'AI-GENERATED', ai_vote: 0, human_vote: 0, description: 'An Astronaut' },
    { id:10, src: '/img/astronaut.jpg', type: 'HUMANMADE', ai_vote: 0, human_vote: 0, description: 'THE END!!' },
  ]

  return (
    <div style={{ textAlign: "center", justifyContent: "center" }}>
      <Routes>
        <Route path="/" element={<HomePage />} />
        <Route path="/final" element={<FinalPage/>} />
        <Route path="/vote/:id" element={<VotePage items={ items }/>} />
        <Route path="/result/:id" element={<ResultPage items={ items } />} />
      </Routes>
    </div>
  );
}
